# Redirect old domain to new primary domain
[[redirects]]
  from = "https://u-movex.com/*"
  to = "https://umovex.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.u-movex.com/*"
  to = "https://umovex.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://u-movex.com/*"
  to = "https://umovex.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.u-movex.com/*"
  to = "https://umovex.com/:splat"
  status = 301
  force = true